#!/usr/bin/env python3
"""gen_recipe_docs.py -- render docs/recipes.md from the shipped recipe library.

Every recipe under ``src/docket/templates/recipes/<name>/`` is documented from what it ships:
its ``pod.yaml`` description, the summary ``core.pod_apply.summarize_recipe`` derives from the
directory, the two commands that apply it, and its own README body. Nothing is typed a second
time, so a recipe cannot be documented differently from what the wheel carries.

Usage:
  ./scripts/gen_recipe_docs.py            # regenerate docs/recipes.md
  ./scripts/gen_recipe_docs.py --check    # exit 1 if the file on disk is stale
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
RECIPES_MD = ROOT / "docs" / "recipes.md"

sys.path.insert(0, str(SRC))

from docket import config as _cfg  # noqa: E402
from docket.core import pod_apply as _pod_apply  # noqa: E402

HEADER = """# The recipe library

<!-- Generated by scripts/gen_recipe_docs.py from src/docket/templates/recipes/. Do not edit. -->

A recipe is a directory in the same shape as a repository's `.docket/`: an optional `pod.yaml`
(`kind: pod`, `name`, `description`, `members`, `settings`), optional `roles/`, `pipeline.yaml`,
`policies/`, `plugins/`, `skills/` and `mcp-servers/`. What a recipe brings is derived from what the directory
holds, never declared; `docket recipes list` prints the same derivation. Apply one with:

```bash
docket init --recipe <name>            # a new pod for the current repository
docket pod <project> apply <name>      # onto a pod that already exists (--dry-run to plan)
docket recipes show <name>             # description, what it brings, its README
```

A directory of your own under `~/.docket/recipes/<name>/` is addressable the same way and wins
over a shipped recipe of the same name. Composition: apply as many recipes as you need, then
`docket pod <project> export` writes the merged team to `.docket/`, the configuration of record.

"""


def _brings(summary: _pod_apply.RecipeSummary) -> str:
    parts: list[str] = []
    for count, singular, plural in (
        (summary.roles, "role", "roles"),
        (summary.policies, "policy", "policies"),
        (summary.members, "member", "members"),
        (summary.skills, "skill", "skills"),
        (summary.plugins, "plugin", "plugins"),
        (summary.settings, "setting", "settings"),
        (len(summary.mcp_servers), "MCP server", "MCP servers"),
    ):
        if count:
            parts.append(f"{count} {singular if count == 1 else plural}")
    if summary.pipeline:
        parts.append(f"pipeline `{summary.pipeline}`")
    return ", ".join(parts) if parts else "nothing"


def _readme_body(directory: Path) -> str:
    """The README with its H1 dropped and every other heading demoted one level."""
    readme = directory / "README.md"
    if not readme.is_file():
        return ""
    out: list[str] = []
    in_fence = False
    for line in readme.read_text(encoding="utf-8").splitlines():
        if line.startswith("```"):
            in_fence = not in_fence
        if not in_fence and line.startswith("# "):
            continue
        if not in_fence and line.startswith("#"):
            line = "#" + line
        out.append(line)
    return "\n".join(out).strip() + "\n"


def render() -> str:
    recipes = sorted(p for p in _cfg.recipes_dir().iterdir() if p.is_dir())
    summaries = {p.name: _pod_apply.summarize_recipe(p) for p in recipes}
    lines = [HEADER, "| Recipe | Brings | Description |", "| --- | --- | --- |"]
    for p in recipes:
        s = summaries[p.name]
        lines.append(f"| [`{p.name}`](#{p.name}) | {_brings(s)} | {s.description} |")
    lines.append("")
    for p in recipes:
        s = summaries[p.name]
        lines.append(f"## {p.name}")
        lines.append("")
        if s.description:
            lines.append(s.description)
            lines.append("")
        lines.append(f"**Brings:** {_brings(s)}. **Summary line:** `{s.render()}`")
        lines.append("")
        lines.append("```bash")
        lines.append(f"docket init --recipe {p.name}")
        lines.append(f"docket pod <project> apply {p.name}")
        lines.append("```")
        lines.append("")
        body = _readme_body(p)
        if body:
            lines.append(body)
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    content = render()
    if "--check" in args:
        current = RECIPES_MD.read_text(encoding="utf-8") if RECIPES_MD.is_file() else ""
        if current != content:
            print(
                "gen_recipe_docs: docs/recipes.md is STALE -- run "
                "`uv run python scripts/gen_recipe_docs.py` to regenerate.",
                file=sys.stderr,
            )
            return 1
        print("gen_recipe_docs: docs/recipes.md is up to date.")
        return 0
    RECIPES_MD.write_text(content, encoding="utf-8")
    print(f"gen_recipe_docs: wrote {RECIPES_MD.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
